# 1. WORKFLOW IDENTITY
name: Run tests
run-name: Run tests. Triggered by ${{ github.actor }}

# 2. TRIGGER EVENTS
on:
  push:
    branches: [ "main" ]

# 4. JOBS AND STEPS
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s .
