# 1. WORKFLOW IDENTITY
name: Daily code checkout
run-name: Daily code checkout triggered by ${{ github.triggering_actor }}

# 2. TRIGGER EVENTS
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# 4. JOBS AND STEPS
jobs:
  run-daily-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Print the message
        run: echo "Scheduled build completed successfully!"
